### ISSUE TITLE
Consider change of SQL library

### ISSUE THREAD

**Issue by akvlad** [metrico/otel-collector#8]
# Current state

In order to send data into the tables the `github.com/ClickHouse/clickhouse-go/v2`  library is used. 
The library is used behind the `database/sql` abstraction adding even more CPU overhead.

On the other hand there is much more effective library [ch-go ](https://github.com/ClickHouse/ch-go). 

# Proposition

As far as we know the schema it's not complicated to migrate to `ch-go`.
Please check the library API and consider the migration.

**Comment by Cluas** [comment]
We can change to native interface. https://github.com/ClickHouse/clickhouse-go#native-interface

**Comment by Cluas** [comment]
In ch-go README.md 
> NB: No pooling, reconnects and not goroutine-safe by default, only single connection. Use [clickhouse-go](https://github.com/ClickHouse/clickhouse-go) for high-level database/sql-compatible client, pooling for ch-go is available as [chpool](https://pkg.go.dev/github.com/ClickHouse/ch-go/chpool) package.

**Comment by Cluas** [comment]
close by #7

**Comment by akvlad** [comment]
I see no usage of `ch-go` lib in main. Why don't we use it?

**Comment by Cluas** [comment]
`ch-go` not support `Nested type` yet. 
If we insist on using it, then we need to modify the trace code to not rely on the traces_input table, `tags` column which type `Array(Tuple(String, String))` can not use in `ch-go`.

**Comment by Cluas** [comment]
https://github.com/ClickHouse/clickhouse-go#benchmark

**Comment by lmangani** [comment]
@Cluas proceed with your choice for now let's maximize progressing forward 👍
