### ISSUE TITLE
error decoding 'processors' 

### ISSUE THREAD

**Issue by gabrielgontariu** [metrico/otel-collector#81]
Hello!

Seems to me that some dependencies got update and how I don't quite get how to write a working config file for the collector

Can you please provide an example?

journalctl -u otel-collector -f
Apr 05 08:14:41 ip-10-151-1-19 otel-collector[7618]: * error decoding 'processors': unknown type: "spanmetrics" for id: "spanmetrics" (valid values: [filter groupbytrace redaction routing tail_sampling batch deltatorate memory_limiter span groupbyattrs k8sattributes experimental_metricsgeneration metricstransform resource schema transform attributes logstransform probabilistic_sampler resourcedetection cumulativetodelta])
Apr 05 08:14:41 ip-10-151-1-19 otel-collector[7618]: 2024/04/05 08:14:41 application run finished with error: failed to get config: cannot unmarshal the configuration: 1 error(s) decoding:
Apr 05 08:14:41 ip-10-151-1-19 otel-collector[7618]: * error decoding 'processors': unknown type: "spanmetrics" for id: "spanmetrics" (valid values: [filter groupbytrace redaction routing tail_sampling batch deltatorate memory_limiter span groupbyattrs k8sattributes experimental_metricsgeneration metricstransform resource schema transform attributes logstransform probabilistic_sampler resourcedetection cumulativetodelta])

**Comment by lmangani** [comment]
Could you share an anonymized version of your config to understand what's there? Or if you're using an example, please confirm which one. Thanks!

**Comment by akvlad** [comment]
According to the readme
https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.95.0/processor/spanmetricsprocessor
> Note: The spanmetrics processor is deprecated in favour of the spanmetrics connector.

So yeah. It disappeared after the major upgrade, please use the spanmetrics connector instead.

**Comment by gabrielgontariu** [comment]
Thanks for the messages!

Ok! I will try updating next week and get back with the results

**Comment by lmangani** [comment]
We need to update our examples accordingly. This is the new [connector example](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.95.0/connector/spanmetricsconnector/README.md#examples)
