### ISSUE TITLE
Difficult code parts in feat-add_metrics_exporter branch

### ISSUE THREAD

**Issue by akvlad** [metrico/otel-collector#9]
Two functions are very complicated to support.
- https://github.com/metrico/otel-collector/blob/feat-add_metrics_exporter/exporter/qrynexporter/metrics.go#L365
- https://github.com/metrico/otel-collector/blob/feat-add_metrics_exporter/exporter/qrynexporter/traces.go#L124

Please
- split the functions
- keep the nesting level no more than 4 
- no more than 4 tabs before the code on a line
- let's keep these recommendations for the future

**Comment by lmangani** [comment]
Moved inline to the PR #7
